platform :ios, '9.0'

target 'PxView' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PxView
  pod 'Fabric'
  pod 'Crashlytics'

  # pod 'react-native-photo-view', :path => '../node_modules/react-native-photo-view'

  pod 'CsSdk', :path => '../node_modules/react-native-cs-sdk'

  node_modules_path = '../node_modules'
  pod 'yoga', path: "#{node_modules_path}/react-native/ReactCommon/yoga/Yoga.podspec"
  pod 'React', path: "#{node_modules_path}/react-native"

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end