# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'PxView' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PxView
  pod 'Fabric'
  pod 'Crashlytics'

  # pod 'react-native-photo-view', :path => '../node_modules/react-native-photo-view'

  pod 'CsSdk', :path => '../node_modules/react-native-cs-sdk'

end
